version: 2

# -------------------------------------------------------------------------------------
# Jobs
# -------------------------------------------------------------------------------------
jobs:
  rununittests:
    docker:
      - image: circleci/python:3.7.4-buster
    working_directory: ~/CrypTen
    steps:
      - checkout
      - run:
          name: Sets up the virtualenv
          command: |
            python3 -m venv ~/crypten-test
            . ~/crypten-test/bin/activate
            pip3 install --upgrade pip
            pip3 install torch==1.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            pip3 install onnx tensorboard future
      - run:
          name: Unit tests
          command: |
            . ~/crypten-test/bin/activate
            echo 'for i in $(ls test/test_*.py | grep -v test_context.py); do python3 -m unittest $i; (($? != 0)) && exit 1; done; exit 0' > run_tests.sh
            bash ./run_tests.sh
      - run:
          name: Linear svm example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py
      - run:
          name: Linear svm example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --epochs 2 --skip_plaintext
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --world_size 2 --multiprocess
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --world_size 4 --multiprocess
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --multiprocess
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            pip3 install torchvision
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 2
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 2
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 1 --multiprocess
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 1 --multiprocess
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 3 --multiprocess --world_size 1 --skip-plaintext
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 3 --multiprocess --world_size 1 --skip-plaintext


# -------------------------------------------------------------------------------------
# Workflows
# -------------------------------------------------------------------------------------
workflows:
  version: 2
  commit:
    jobs:
      - rununittests
